// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjmqufhhnrllijfeeynt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqbXF1ZmhobnJsbGlqZmVleW50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTkxNTQsImV4cCI6MjA1OTg5NTE1NH0.KRhE0c4pYRzUbHAmwBLAKI-BdArGH4Fj8HRbG5HZNfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);